export const styles = {
  root: {
    minHeight: 'calc(100vh - 48px)',
  },
  headerRoot: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    height: '50px',
    borderBottom: '1px solid #e8e8e8',
  },
  headerTxt: {
    fontSize: '20px',
    fontWeight: 500,
  },
  orderFoldingSectionLabelRoot: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  orderFoldingSectionLabel: {},
  orderFoldingSectionCount: { fontSize: '14px' },
  ordererFoldingSectionRoot: { padding: '20px' },
  ordererFoldingSectionPhoneRoot: { marginTop: '20px' },
  submitAddressRoot: {
    padding: '16px 20px',
    background: 'ellow',
    borderTop: '1px solid #e8e8e8',
    borderBottom: '1px solid #e8e8e8',
  },
  submitAddressBtnRoot: {
    padding: '10px 0px',
    display: 'flex',
    justifyContent: 'center',
    textAlign: 'center',
    borderRadius: '4px',
    borderWidth: '1px',
    borderColor: '#8a8a8a',
    borderStyle: 'solid',
  },
  submitAddressTxt: { fontSize: '14px' },
  agreeRoot: {
    padding: '20px',
    marginBottom: '140px',
  },
  buyBtn: {
    position: 'fixed',
    top: 'auto',
    bottom: 0,
    maxWidth: '1000px',
    fontWeight: 700,
    fontSize: '19px',
    width: '100vw',
    height: '64px',
    color: 'white',
    background: 'black',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderTopLeftRadius: '20px',
    borderTopRightRadius: '20px',
  },
};
