export const styles = {
  root: { borderBottom: '16px solid #f0f0f0' },
  headerRoot: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    height: '60px',
    padding: '0px 20px',
    borderBottom: '1px solid #f0f0f0',
  },
  headerDateTxt: {
    fontSize: '16px',
    fontWeight: 700,
  },
  headerDetailBtnTxt: { fontSize: '14px', color: '#0476e9' },
  headerDetailIcon: { color: '#0476e9' },
  orderStateRoot: {
    padding: '0px 20px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottom: '1px solid #f0f0f0',
    height: '50px',
  },
  stateCompleteRoot: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: 'black',
    borderRadius: '2px',
    width: 'fit-content',
    marginLeft: '6px',
  },
  stateCompleteTxt: {
    fontSize: '14px',
    fontWeight: 700,
    padding: '4px 8px',
    color: 'white',
  },

  stateProceedRoot: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: '#f5f6f9',
    borderRadius: '2px',
    width: 'fit-content',
    marginLeft: '6px',
  },
  stateProceedTxt: { fontSize: '14px', fontWeight: 500, padding: '4px 8px' },

  orderStateTxt: {
    fontSize: '14px',
  },
  cardRoot: { borderRadius: '0px', borderBottom: '2px solid #e1e1e1' },
  cardActionAreaRoot: {
    display: 'flex',
    justifyContent: 'start',
    alignItems: 'start',
    padding: '16px 20px',
  },
  thumbnailAreaRoot: {
    position: 'relative',
    marginRight: '12px',
  },
  thumbnailImg: { borderRadius: '3px' },
  contentsRoot: {
    display: 'flex',
    height: '110px',
    flexDirection: 'column',
    justifyContent: 'space-between',
    padding: 0,
    margin: 0,
  },
  titleRoot: {},
  title: {
    textAlign: 'left',
    lineHeight: '1.5',
    fontSize: 14,
    fontWeight: '500',
    whiteSpace: 'pre-wrap',
    display: '-webkit-box',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    WebkitLineClamp: '1',
    WebkitBoxOrient: 'vertical',
  },
  priceRoot: {
    display: 'flex',
    alignItems: 'center',
  },
  priceTxt: { fontSize: '16px', fontWeight: 700 },
  priceSubTxt: { fontSize: '13px' },
  subInfoTxt: {
    color: 'gray',
    fontSize: '12px',
    fontWeight: 500,
    whiteSpace: 'pre-wrap',
    display: '-webkit-box',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    WebkitLineClamp: '1',
    WebkitBoxOrient: 'vertical',
  },
};
